#!/command/with-contenv bash
export HOME=/home/ubuntu
exec s6-setuidgid ubuntu \
  code serve-web \
    --host ${BIND_ADDR:-0.0.0.0} \
    --port 8080 \
    --without-connection-token \
    --accept-server-license-terms
